// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { asTextContentResult } from 'app-store-connect-api-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Metadata } from '../';
import AppStoreConnectAPI from 'app-store-connect-api';

export const metadata: Metadata = {
  resource: 'sandbox_testers',
  operation: 'write',
  tags: [],
  httpMethod: 'patch',
  httpPath: '/v2/sandboxTesters/{id}',
  operationId: 'sandboxTestersV2_updateInstance',
};

export const tool: Tool = {
  name: 'update_sandbox_testers',
  description: '',
  inputSchema: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
      },
      data: {
        type: 'object',
        properties: {
          id: {
            type: 'string',
          },
          type: {
            type: 'string',
            enum: ['sandboxTesters'],
          },
          attributes: {
            type: 'object',
            properties: {
              interruptPurchases: {
                type: 'boolean',
              },
              subscriptionRenewalRate: {
                type: 'string',
                enum: [
                  'MONTHLY_RENEWAL_EVERY_ONE_HOUR',
                  'MONTHLY_RENEWAL_EVERY_THIRTY_MINUTES',
                  'MONTHLY_RENEWAL_EVERY_FIFTEEN_MINUTES',
                  'MONTHLY_RENEWAL_EVERY_FIVE_MINUTES',
                  'MONTHLY_RENEWAL_EVERY_THREE_MINUTES',
                ],
              },
              territory: {
                $ref: '#/$defs/territory_code',
              },
            },
            required: [],
          },
        },
        required: ['id', 'type'],
      },
    },
    $defs: {
      territory_code: {
        type: 'string',
        enum: [
          'ABW',
          'AFG',
          'AGO',
          'AIA',
          'ALB',
          'AND',
          'ANT',
          'ARE',
          'ARG',
          'ARM',
          'ASM',
          'ATG',
          'AUS',
          'AUT',
          'AZE',
          'BDI',
          'BEL',
          'BEN',
          'BES',
          'BFA',
          'BGD',
          'BGR',
          'BHR',
          'BHS',
          'BIH',
          'BLR',
          'BLZ',
          'BMU',
          'BOL',
          'BRA',
          'BRB',
          'BRN',
          'BTN',
          'BWA',
          'CAF',
          'CAN',
          'CHE',
          'CHL',
          'CHN',
          'CIV',
          'CMR',
          'COD',
          'COG',
          'COK',
          'COL',
          'COM',
          'CPV',
          'CRI',
          'CUB',
          'CUW',
          'CXR',
          'CYM',
          'CYP',
          'CZE',
          'DEU',
          'DJI',
          'DMA',
          'DNK',
          'DOM',
          'DZA',
          'ECU',
          'EGY',
          'ERI',
          'ESP',
          'EST',
          'ETH',
          'FIN',
          'FJI',
          'FLK',
          'FRA',
          'FRO',
          'FSM',
          'GAB',
          'GBR',
          'GEO',
          'GGY',
          'GHA',
          'GIB',
          'GIN',
          'GLP',
          'GMB',
          'GNB',
          'GNQ',
          'GRC',
          'GRD',
          'GRL',
          'GTM',
          'GUF',
          'GUM',
          'GUY',
          'HKG',
          'HND',
          'HRV',
          'HTI',
          'HUN',
          'IDN',
          'IMN',
          'IND',
          'IRL',
          'IRQ',
          'ISL',
          'ISR',
          'ITA',
          'JAM',
          'JEY',
          'JOR',
          'JPN',
          'KAZ',
          'KEN',
          'KGZ',
          'KHM',
          'KIR',
          'KNA',
          'KOR',
          'KWT',
          'LAO',
          'LBN',
          'LBR',
          'LBY',
          'LCA',
          'LIE',
          'LKA',
          'LSO',
          'LTU',
          'LUX',
          'LVA',
          'MAC',
          'MAR',
          'MCO',
          'MDA',
          'MDG',
          'MDV',
          'MEX',
          'MHL',
          'MKD',
          'MLI',
          'MLT',
          'MMR',
          'MNE',
          'MNG',
          'MNP',
          'MOZ',
          'MRT',
          'MSR',
          'MTQ',
          'MUS',
          'MWI',
          'MYS',
          'MYT',
          'NAM',
          'NCL',
          'NER',
          'NFK',
          'NGA',
          'NIC',
          'NIU',
          'NLD',
          'NOR',
          'NPL',
          'NRU',
          'NZL',
          'OMN',
          'PAK',
          'PAN',
          'PER',
          'PHL',
          'PLW',
          'PNG',
          'POL',
          'PRI',
          'PRT',
          'PRY',
          'PSE',
          'PYF',
          'QAT',
          'REU',
          'ROU',
          'RUS',
          'RWA',
          'SAU',
          'SEN',
          'SGP',
          'SHN',
          'SLB',
          'SLE',
          'SLV',
          'SMR',
          'SOM',
          'SPM',
          'SRB',
          'SSD',
          'STP',
          'SUR',
          'SVK',
          'SVN',
          'SWE',
          'SWZ',
          'SXM',
          'SYC',
          'TCA',
          'TCD',
          'TGO',
          'THA',
          'TJK',
          'TKM',
          'TLS',
          'TON',
          'TTO',
          'TUN',
          'TUR',
          'TUV',
          'TWN',
          'TZA',
          'UGA',
          'UKR',
          'UMI',
          'URY',
          'USA',
          'UZB',
          'VAT',
          'VCT',
          'VEN',
          'VGB',
          'VIR',
          'VNM',
          'VUT',
          'WLF',
          'WSM',
          'YEM',
          'ZAF',
          'ZMB',
          'ZWE',
        ],
      },
    },
  },
};

export const handler = async (client: AppStoreConnectAPI, args: Record<string, unknown> | undefined) => {
  const { id, ...body } = args as any;
  return asTextContentResult(await client.sandboxTesters.update(id, body));
};

export default { metadata, tool, handler };
