// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Metadata, asTextContentResult } from 'app-store-connect-api-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import AppStoreConnectAPI from 'app-store-connect-api';

export const metadata: Metadata = {
  resource: 'apps',
  operation: 'read',
  tags: [],
  httpMethod: 'get',
  httpPath: '/v1/apps/{id}/customerReviews',
  operationId: 'apps_customerReviews_getToManyRelated',
};

export const tool: Tool = {
  name: 'retrieve_customer_reviews_apps',
  description:
    "When using this tool, always use the `jq_filter` parameter to reduce the response size and improve performance.\n\nOnly omit if you're sure you don't need the data.\n\n",
  inputSchema: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
      },
      'exists[publishedResponse]': {
        type: 'boolean',
        description: 'filter by publishedResponse',
      },
      'fields[customerReviewResponses]': {
        type: 'array',
        description: 'the fields to include for returned resources of type customerReviewResponses',
        items: {
          type: 'string',
          enum: ['responseBody', 'lastModifiedDate', 'state', 'review'],
        },
      },
      'fields[customerReviews]': {
        type: 'array',
        description: 'the fields to include for returned resources of type customerReviews',
        items: {
          type: 'string',
          enum: ['rating', 'title', 'body', 'reviewerNickname', 'createdDate', 'territory', 'response'],
        },
      },
      'filter[rating]': {
        type: 'array',
        description: "filter by attribute 'rating'",
        items: {
          type: 'string',
        },
      },
      'filter[territory]': {
        type: 'array',
        description: "filter by attribute 'territory'",
        items: {
          type: 'string',
          enum: [
            'ABW',
            'AFG',
            'AGO',
            'AIA',
            'ALB',
            'AND',
            'ANT',
            'ARE',
            'ARG',
            'ARM',
            'ASM',
            'ATG',
            'AUS',
            'AUT',
            'AZE',
            'BDI',
            'BEL',
            'BEN',
            'BES',
            'BFA',
            'BGD',
            'BGR',
            'BHR',
            'BHS',
            'BIH',
            'BLR',
            'BLZ',
            'BMU',
            'BOL',
            'BRA',
            'BRB',
            'BRN',
            'BTN',
            'BWA',
            'CAF',
            'CAN',
            'CHE',
            'CHL',
            'CHN',
            'CIV',
            'CMR',
            'COD',
            'COG',
            'COK',
            'COL',
            'COM',
            'CPV',
            'CRI',
            'CUB',
            'CUW',
            'CXR',
            'CYM',
            'CYP',
            'CZE',
            'DEU',
            'DJI',
            'DMA',
            'DNK',
            'DOM',
            'DZA',
            'ECU',
            'EGY',
            'ERI',
            'ESP',
            'EST',
            'ETH',
            'FIN',
            'FJI',
            'FLK',
            'FRA',
            'FRO',
            'FSM',
            'GAB',
            'GBR',
            'GEO',
            'GGY',
            'GHA',
            'GIB',
            'GIN',
            'GLP',
            'GMB',
            'GNB',
            'GNQ',
            'GRC',
            'GRD',
            'GRL',
            'GTM',
            'GUF',
            'GUM',
            'GUY',
            'HKG',
            'HND',
            'HRV',
            'HTI',
            'HUN',
            'IDN',
            'IMN',
            'IND',
            'IRL',
            'IRQ',
            'ISL',
            'ISR',
            'ITA',
            'JAM',
            'JEY',
            'JOR',
            'JPN',
            'KAZ',
            'KEN',
            'KGZ',
            'KHM',
            'KIR',
            'KNA',
            'KOR',
            'KWT',
            'LAO',
            'LBN',
            'LBR',
            'LBY',
            'LCA',
            'LIE',
            'LKA',
            'LSO',
            'LTU',
            'LUX',
            'LVA',
            'MAC',
            'MAR',
            'MCO',
            'MDA',
            'MDG',
            'MDV',
            'MEX',
            'MHL',
            'MKD',
            'MLI',
            'MLT',
            'MMR',
            'MNE',
            'MNG',
            'MNP',
            'MOZ',
            'MRT',
            'MSR',
            'MTQ',
            'MUS',
            'MWI',
            'MYS',
            'MYT',
            'NAM',
            'NCL',
            'NER',
            'NFK',
            'NGA',
            'NIC',
            'NIU',
            'NLD',
            'NOR',
            'NPL',
            'NRU',
            'NZL',
            'OMN',
            'PAK',
            'PAN',
            'PER',
            'PHL',
            'PLW',
            'PNG',
            'POL',
            'PRI',
            'PRT',
            'PRY',
            'PSE',
            'PYF',
            'QAT',
            'REU',
            'ROU',
            'RUS',
            'RWA',
            'SAU',
            'SEN',
            'SGP',
            'SHN',
            'SLB',
            'SLE',
            'SLV',
            'SMR',
            'SOM',
            'SPM',
            'SRB',
            'SSD',
            'STP',
            'SUR',
            'SVK',
            'SVN',
            'SWE',
            'SWZ',
            'SXM',
            'SYC',
            'TCA',
            'TCD',
            'TGO',
            'THA',
            'TJK',
            'TKM',
            'TLS',
            'TON',
            'TTO',
            'TUN',
            'TUR',
            'TUV',
            'TWN',
            'TZA',
            'UGA',
            'UKR',
            'UMI',
            'URY',
            'USA',
            'UZB',
            'VAT',
            'VCT',
            'VEN',
            'VGB',
            'VIR',
            'VNM',
            'VUT',
            'WLF',
            'WSM',
            'YEM',
            'ZAF',
            'ZMB',
            'ZWE',
          ],
        },
      },
      include: {
        type: 'array',
        description: 'comma-separated list of relationships to include',
        items: {
          type: 'string',
          enum: ['response'],
        },
      },
      limit: {
        type: 'integer',
        description: 'maximum resources per page',
      },
      sort: {
        type: 'array',
        description: 'comma-separated list of sort expressions; resources will be sorted as specified',
        items: {
          type: 'string',
          enum: ['rating', '-rating', 'createdDate', '-createdDate'],
        },
      },
    },
  },
};

export const handler = async (client: AppStoreConnectAPI, args: Record<string, unknown> | undefined) => {
  const { id, ...body } = args as any;
  return asTextContentResult(await client.apps.retrieveCustomerReviews(id, body));
};

export default { metadata, tool, handler };
