// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Metadata, asTextContentResult } from 'app-store-connect-api-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import AppStoreConnectAPI from 'app-store-connect-api';

export const metadata: Metadata = {
  resource: 'ci_products',
  operation: 'read',
  tags: [],
  httpMethod: 'get',
  httpPath: '/v1/ciProducts/{id}/app',
  operationId: 'ciProducts_app_getToOneRelated',
};

export const tool: Tool = {
  name: 'retrieve_app_ci_products',
  description:
    "When using this tool, always use the `jq_filter` parameter to reduce the response size and improve performance.\n\nOnly omit if you're sure you don't need the data.\n\n",
  inputSchema: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
      },
      'fields[appClips]': {
        type: 'array',
        description: 'the fields to include for returned resources of type appClips',
        items: {
          type: 'string',
          enum: ['bundleId', 'app', 'appClipDefaultExperiences', 'appClipAdvancedExperiences'],
        },
      },
      'fields[appCustomProductPages]': {
        type: 'array',
        description: 'the fields to include for returned resources of type appCustomProductPages',
        items: {
          type: 'string',
          enum: ['name', 'url', 'visible', 'app', 'appCustomProductPageVersions'],
        },
      },
      'fields[appEncryptionDeclarations]': {
        type: 'array',
        description: 'the fields to include for returned resources of type appEncryptionDeclarations',
        items: {
          type: 'string',
          enum: [
            'appDescription',
            'createdDate',
            'usesEncryption',
            'exempt',
            'containsProprietaryCryptography',
            'containsThirdPartyCryptography',
            'availableOnFrenchStore',
            'platform',
            'uploadedDate',
            'documentUrl',
            'documentName',
            'documentType',
            'appEncryptionDeclarationState',
            'codeValue',
            'app',
            'builds',
            'appEncryptionDeclarationDocument',
          ],
        },
      },
      'fields[appEvents]': {
        type: 'array',
        description: 'the fields to include for returned resources of type appEvents',
        items: {
          type: 'string',
          enum: [
            'referenceName',
            'badge',
            'eventState',
            'deepLink',
            'purchaseRequirement',
            'primaryLocale',
            'priority',
            'purpose',
            'territorySchedules',
            'archivedTerritorySchedules',
            'localizations',
          ],
        },
      },
      'fields[appInfos]': {
        type: 'array',
        description: 'the fields to include for returned resources of type appInfos',
        items: {
          type: 'string',
          enum: [
            'appStoreState',
            'state',
            'appStoreAgeRating',
            'australiaAgeRating',
            'brazilAgeRating',
            'brazilAgeRatingV2',
            'franceAgeRating',
            'koreaAgeRating',
            'kidsAgeBand',
            'app',
            'ageRatingDeclaration',
            'appInfoLocalizations',
            'primaryCategory',
            'primarySubcategoryOne',
            'primarySubcategoryTwo',
            'secondaryCategory',
            'secondarySubcategoryOne',
            'secondarySubcategoryTwo',
          ],
        },
      },
      'fields[apps]': {
        type: 'array',
        description: 'the fields to include for returned resources of type apps',
        items: {
          type: 'string',
          enum: [
            'accessibilityUrl',
            'name',
            'bundleId',
            'sku',
            'primaryLocale',
            'isOrEverWasMadeForKids',
            'subscriptionStatusUrl',
            'subscriptionStatusUrlVersion',
            'subscriptionStatusUrlForSandbox',
            'subscriptionStatusUrlVersionForSandbox',
            'contentRightsDeclaration',
            'streamlinedPurchasingEnabled',
            'accessibilityDeclarations',
            'appEncryptionDeclarations',
            'ciProduct',
            'betaTesters',
            'betaGroups',
            'appStoreVersions',
            'preReleaseVersions',
            'betaAppLocalizations',
            'builds',
            'betaLicenseAgreement',
            'betaAppReviewDetail',
            'appInfos',
            'appClips',
            'appPricePoints',
            'endUserLicenseAgreement',
            'appPriceSchedule',
            'appAvailabilityV2',
            'inAppPurchases',
            'subscriptionGroups',
            'gameCenterEnabledVersions',
            'perfPowerMetrics',
            'appCustomProductPages',
            'inAppPurchasesV2',
            'promotedPurchases',
            'appEvents',
            'reviewSubmissions',
            'subscriptionGracePeriod',
            'customerReviews',
            'customerReviewSummarizations',
            'gameCenterDetail',
            'appStoreVersionExperimentsV2',
            'alternativeDistributionKey',
            'analyticsReportRequests',
            'marketplaceSearchDetail',
            'backgroundAssets',
            'betaFeedbackScreenshotSubmissions',
            'betaFeedbackCrashSubmissions',
            'webhooks',
          ],
        },
      },
      'fields[appStoreVersionExperiments]': {
        type: 'array',
        description: 'the fields to include for returned resources of type appStoreVersionExperiments',
        items: {
          type: 'string',
          enum: [
            'name',
            'platform',
            'trafficProportion',
            'state',
            'reviewRequired',
            'startDate',
            'endDate',
            'app',
            'latestControlVersion',
            'controlVersions',
            'appStoreVersionExperimentTreatments',
          ],
        },
      },
      'fields[appStoreVersions]': {
        type: 'array',
        description: 'the fields to include for returned resources of type appStoreVersions',
        items: {
          type: 'string',
          enum: [
            'platform',
            'versionString',
            'appStoreState',
            'appVersionState',
            'copyright',
            'reviewType',
            'releaseType',
            'earliestReleaseDate',
            'usesIdfa',
            'downloadable',
            'createdDate',
            'app',
            'ageRatingDeclaration',
            'appStoreVersionLocalizations',
            'build',
            'appStoreVersionPhasedRelease',
            'gameCenterAppVersion',
            'routingAppCoverage',
            'appStoreReviewDetail',
            'appStoreVersionSubmission',
            'appClipDefaultExperience',
            'appStoreVersionExperiments',
            'appStoreVersionExperimentsV2',
            'customerReviews',
            'alternativeDistributionPackage',
          ],
        },
      },
      'fields[betaAppLocalizations]': {
        type: 'array',
        description: 'the fields to include for returned resources of type betaAppLocalizations',
        items: {
          type: 'string',
          enum: [
            'feedbackEmail',
            'marketingUrl',
            'privacyPolicyUrl',
            'tvOsPrivacyPolicy',
            'description',
            'locale',
            'app',
          ],
        },
      },
      'fields[betaAppReviewDetails]': {
        type: 'array',
        description: 'the fields to include for returned resources of type betaAppReviewDetails',
        items: {
          type: 'string',
          enum: [
            'contactFirstName',
            'contactLastName',
            'contactPhone',
            'contactEmail',
            'demoAccountName',
            'demoAccountPassword',
            'demoAccountRequired',
            'notes',
            'app',
          ],
        },
      },
      'fields[betaGroups]': {
        type: 'array',
        description: 'the fields to include for returned resources of type betaGroups',
        items: {
          type: 'string',
          enum: [
            'name',
            'createdDate',
            'isInternalGroup',
            'hasAccessToAllBuilds',
            'publicLinkEnabled',
            'publicLinkId',
            'publicLinkLimitEnabled',
            'publicLinkLimit',
            'publicLink',
            'feedbackEnabled',
            'iosBuildsAvailableForAppleSiliconMac',
            'iosBuildsAvailableForAppleVision',
            'app',
            'builds',
            'betaTesters',
            'betaRecruitmentCriteria',
            'betaRecruitmentCriterionCompatibleBuildCheck',
          ],
        },
      },
      'fields[betaLicenseAgreements]': {
        type: 'array',
        description: 'the fields to include for returned resources of type betaLicenseAgreements',
        items: {
          type: 'string',
          enum: ['agreementText', 'app'],
        },
      },
      'fields[builds]': {
        type: 'array',
        description: 'the fields to include for returned resources of type builds',
        items: {
          type: 'string',
          enum: [
            'version',
            'uploadedDate',
            'expirationDate',
            'expired',
            'minOsVersion',
            'lsMinimumSystemVersion',
            'computedMinMacOsVersion',
            'computedMinVisionOsVersion',
            'iconAssetToken',
            'processingState',
            'buildAudienceType',
            'usesNonExemptEncryption',
            'preReleaseVersion',
            'individualTesters',
            'betaGroups',
            'betaBuildLocalizations',
            'appEncryptionDeclaration',
            'betaAppReviewSubmission',
            'app',
            'buildBetaDetail',
            'appStoreVersion',
            'icons',
            'buildBundles',
            'perfPowerMetrics',
            'diagnosticSignatures',
          ],
        },
      },
      'fields[ciProducts]': {
        type: 'array',
        description: 'the fields to include for returned resources of type ciProducts',
        items: {
          type: 'string',
          enum: [
            'name',
            'createdDate',
            'productType',
            'app',
            'bundleId',
            'workflows',
            'primaryRepositories',
            'additionalRepositories',
            'buildRuns',
          ],
        },
      },
      'fields[endUserLicenseAgreements]': {
        type: 'array',
        description: 'the fields to include for returned resources of type endUserLicenseAgreements',
        items: {
          type: 'string',
          enum: ['agreementText', 'app', 'territories'],
        },
      },
      'fields[gameCenterDetails]': {
        type: 'array',
        description: 'the fields to include for returned resources of type gameCenterDetails',
        items: {
          type: 'string',
          enum: [
            'arcadeEnabled',
            'challengeEnabled',
            'app',
            'gameCenterAppVersions',
            'gameCenterGroup',
            'gameCenterLeaderboards',
            'gameCenterLeaderboardSets',
            'gameCenterAchievements',
            'gameCenterActivities',
            'gameCenterChallenges',
            'defaultLeaderboard',
            'defaultGroupLeaderboard',
            'achievementReleases',
            'activityReleases',
            'challengeReleases',
            'leaderboardReleases',
            'leaderboardSetReleases',
            'challengesMinimumPlatformVersions',
          ],
        },
      },
      'fields[gameCenterEnabledVersions]': {
        type: 'array',
        description: 'the fields to include for returned resources of type gameCenterEnabledVersions',
        items: {
          type: 'string',
          enum: ['platform', 'versionString', 'iconAsset', 'compatibleVersions', 'app'],
        },
      },
      'fields[inAppPurchases]': {
        type: 'array',
        description: 'the fields to include for returned resources of type inAppPurchases',
        items: {
          type: 'string',
          enum: [
            'referenceName',
            'productId',
            'inAppPurchaseType',
            'state',
            'apps',
            'name',
            'reviewNote',
            'familySharable',
            'contentHosting',
            'inAppPurchaseLocalizations',
            'pricePoints',
            'content',
            'appStoreReviewScreenshot',
            'promotedPurchase',
            'iapPriceSchedule',
            'inAppPurchaseAvailability',
            'images',
          ],
        },
      },
      'fields[preReleaseVersions]': {
        type: 'array',
        description: 'the fields to include for returned resources of type preReleaseVersions',
        items: {
          type: 'string',
          enum: ['version', 'platform', 'builds', 'app'],
        },
      },
      'fields[promotedPurchases]': {
        type: 'array',
        description: 'the fields to include for returned resources of type promotedPurchases',
        items: {
          type: 'string',
          enum: ['visibleForAllUsers', 'enabled', 'state', 'inAppPurchaseV2', 'subscription'],
        },
      },
      'fields[reviewSubmissions]': {
        type: 'array',
        description: 'the fields to include for returned resources of type reviewSubmissions',
        items: {
          type: 'string',
          enum: [
            'platform',
            'submittedDate',
            'state',
            'app',
            'items',
            'appStoreVersionForReview',
            'submittedByActor',
            'lastUpdatedByActor',
          ],
        },
      },
      'fields[subscriptionGracePeriods]': {
        type: 'array',
        description: 'the fields to include for returned resources of type subscriptionGracePeriods',
        items: {
          type: 'string',
          enum: ['optIn', 'sandboxOptIn', 'duration', 'renewalType'],
        },
      },
      'fields[subscriptionGroups]': {
        type: 'array',
        description: 'the fields to include for returned resources of type subscriptionGroups',
        items: {
          type: 'string',
          enum: ['referenceName', 'subscriptions', 'subscriptionGroupLocalizations'],
        },
      },
      include: {
        type: 'array',
        description: 'comma-separated list of relationships to include',
        items: {
          type: 'string',
          enum: [
            'appEncryptionDeclarations',
            'ciProduct',
            'betaGroups',
            'appStoreVersions',
            'preReleaseVersions',
            'betaAppLocalizations',
            'builds',
            'betaLicenseAgreement',
            'betaAppReviewDetail',
            'appInfos',
            'appClips',
            'endUserLicenseAgreement',
            'inAppPurchases',
            'subscriptionGroups',
            'gameCenterEnabledVersions',
            'appCustomProductPages',
            'inAppPurchasesV2',
            'promotedPurchases',
            'appEvents',
            'reviewSubmissions',
            'subscriptionGracePeriod',
            'gameCenterDetail',
            'appStoreVersionExperimentsV2',
          ],
        },
      },
      'limit[appClips]': {
        type: 'integer',
        description: 'maximum number of related appClips returned (when they are included)',
      },
      'limit[appCustomProductPages]': {
        type: 'integer',
        description: 'maximum number of related appCustomProductPages returned (when they are included)',
      },
      'limit[appEncryptionDeclarations]': {
        type: 'integer',
        description: 'maximum number of related appEncryptionDeclarations returned (when they are included)',
      },
      'limit[appEvents]': {
        type: 'integer',
        description: 'maximum number of related appEvents returned (when they are included)',
      },
      'limit[appInfos]': {
        type: 'integer',
        description: 'maximum number of related appInfos returned (when they are included)',
      },
      'limit[appStoreVersionExperimentsV2]': {
        type: 'integer',
        description:
          'maximum number of related appStoreVersionExperimentsV2 returned (when they are included)',
      },
      'limit[appStoreVersions]': {
        type: 'integer',
        description: 'maximum number of related appStoreVersions returned (when they are included)',
      },
      'limit[betaAppLocalizations]': {
        type: 'integer',
        description: 'maximum number of related betaAppLocalizations returned (when they are included)',
      },
      'limit[betaGroups]': {
        type: 'integer',
        description: 'maximum number of related betaGroups returned (when they are included)',
      },
      'limit[builds]': {
        type: 'integer',
        description: 'maximum number of related builds returned (when they are included)',
      },
      'limit[gameCenterEnabledVersions]': {
        type: 'integer',
        description: 'maximum number of related gameCenterEnabledVersions returned (when they are included)',
      },
      'limit[inAppPurchases]': {
        type: 'integer',
        description: 'maximum number of related inAppPurchases returned (when they are included)',
      },
      'limit[inAppPurchasesV2]': {
        type: 'integer',
        description: 'maximum number of related inAppPurchasesV2 returned (when they are included)',
      },
      'limit[preReleaseVersions]': {
        type: 'integer',
        description: 'maximum number of related preReleaseVersions returned (when they are included)',
      },
      'limit[promotedPurchases]': {
        type: 'integer',
        description: 'maximum number of related promotedPurchases returned (when they are included)',
      },
      'limit[reviewSubmissions]': {
        type: 'integer',
        description: 'maximum number of related reviewSubmissions returned (when they are included)',
      },
      'limit[subscriptionGroups]': {
        type: 'integer',
        description: 'maximum number of related subscriptionGroups returned (when they are included)',
      },
    },
  },
};

export const handler = async (client: AppStoreConnectAPI, args: Record<string, unknown> | undefined) => {
  const { id, ...body } = args as any;
  return asTextContentResult(await client.ciProducts.retrieveApp(id, body));
};

export default { metadata, tool, handler };
